# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'Example' do
  use_frameworks!
  pod 'LPSnackbar', :path => '../../LPSnackbar', :branch => 'develop'
end
